---
# tasks file for ansible-freeipa-server

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_lsb.id|d(ansible_distribution) }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['freeipa-server', 'freeipa-server-install']

- name: Importing configurations tasks
  import_tasks: configure.yml
  tags: ['freeipa-server', 'freeipa-server-configure']

- name: Optionally including facts tasks
  include_tasks: facts.yml
  when: freeipa_server__facts|bool
  tags: ['freeipa-server', 'freeipa-server-facts']
